---

language: rust
rust: stable

cache: cargo

install:
- ci/install.sh

matrix:
  include:
  - env: TARGET=x86_64-unknown-freebsd
    script: cargo build --target=$TARGET
  - env: TARGET=i686-unknown-freebsd
    script: cargo build --target=$TARGET
    addons:
      apt:
        packages:
          - libc6-dev:i386
          - gcc-multilib
  - env: TARGET="x86_64-unknown-freebsd i686-unknown-freebsd"
    script: ci/docs.sh
